# Generated by Django 6.0.5 on 2026-07-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Parfüm Adı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Fiyat (TL)')),
                ('image', models.ImageField(upload_to='perfumes/', verbose_name='Görsel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Satışta mı?')),
            ],
        ),
    ]
