# Generated by Django 6.0.5 on 2026-07-23 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Slug')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.AlterModelOptions(
            name='perfume',
            options={'verbose_name': 'Parfüm', 'verbose_name_plural': 'Parfümler'},
        ),
        migrations.AddField(
            model_name='perfume',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfumes', to='catalog.category', verbose_name='Kategori'),
        ),
    ]
