from django.core.management.base import BaseCommand
from catalog.models import Category, Perfume

class Command(BaseCommand):
    help = 'Tüm 219 parfümü ve özel açıklamalarını veritabanına toplu olarak yükler.'

    def handle(self, *args, **kwargs):
        perfume_data = [
            # 1-21
            ("MEGAMARE", "Erkek", "Okyanusun hırçın, derin ve tuzlu esintilerini taşıyan, inanılmaz kalıcılığa sahip karakteristik bir deniz kokusu."),
            ("LANCOME LA VIE EST BELLE X", "Kadın", "İris, yasemin ve portakal çiçeğinin zarif uyumuyla harmanlanmış, tatlı ve pudralı efsanevi bir parfüm."),
            ("DIOR FAHRENHEIT", "Erkek", "Deri, odunsu notalar ve menekşenin maskülen birleşimiyle parfüm dünyasında çığır açan klasik bir başyapıt."),
            ("ARMANI STRONGER WITH YOU", "Erkek", "Kestane, vanilya ve baharatların sıcak dokunuşuyla öne çıkan, modern, tatlı ve son derece çekici bir koku."),
            ("LACOSTE POUR FEMME", "Kadın", "Frezya ve Jamaika biberinin ferahlığıyla açılan; zarif, pudralı ve tenle bütünleşen yumuşak bir klasik."),
            ("BVLGARI TYGAR", "Erkek", "Greyfurtun parlak enerjisi ve ambroksanın derin odunsu karakteriyle buluştuğu lüks bir narenciye şaheseri."),
            ("CHANEL COCO MADEMOISELLE", "Kadın", "Canlı portakal, saf yasemin ve paçulinin asil birleşimi. Bağımsız, modern ve zamansız bir zarafet."),
            ("ARMANI ACQUA DI GIO", "Erkek", "Deniz notaları ve ferah turunçgillerin mükemmel dengesi. Yıllara meydan okuyan ikonik bir Akdeniz rüzgarı."),
            ("TOM FORD BITTER PEACH", "Unisex", "Olgunlaşmış şeftalinin, kan portakalı ve rom ile kışkırtıcı bir şekilde harmanlandığı yoğun bir niş tasarım."),
            ("VERSACE CRYSTAL NOIR", "Kadın", "Hindistan cevizi, biber ve gardenyanın karanlık, kremsi ve baharatlı buluşması. Büyüleyici bir gece kokusu."),
            ("PACO RABANNE OLYMPEA X", "Kadın", "Tuzlu vanilya ve su yasemininin eşsiz kontrastı. Güçlü, feminen ve baş döndürücü bir cazibe."),
            ("BACCARAT ROUGE 540", "Unisex", "Yasemin, safran, sedir ağacı ve amberin efsanevi buluşması. Tende kristalize olan hafızalara kazınan bir başyapıt."),
            ("PACO RABANNE INVICTUS", "Erkek", "Greyfurt, deniz notaları ve defne yaprağının dinamik uyumu. Zaferin ve gücün ferahlatıcı kokusu."),
            ("PACO RABANNE ONE MILLION", "Erkek", "Kan mandalinası, tarçın ve derinin kışkırtıcı harmanı. Altının ihtişamını yansıtan iddialı bir klasik."),
            ("VERSACE EROS X", "Erkek", "Nane, yeşil elma ve madagaskar vanilyası. Tutkulu, tatlı, ferah ve baş döndürücü bir gece kokusu."),
            ("DIOR SAUVAGE", "Erkek", "Calabrian bergamotu, ambroksan ve karabiberin vurucu birleşimi. Vahşi doğadan ilham alan, taze ve maskülen."),
            ("VERSACE EROS POUR FEMME", "Kadın", "Sicilya limonu, nar ve saf yaseminin büyüleyici dansı. Baştan çıkarıcı ve aydınlık bir feminenlik."),
            ("KILIAN LOVE DONT BE SHY", "Kadın", "Portakal çiçeği, vanilya ve marshmallow notalarıyla enfes bir gurmand. Bağımlılık yaratan bir afrodizyak."),
            ("EX NIHILO FLEUR NARCOTIQUE", "Unisex", "Şeftali, liçi ve şakayığın zarif, meyvemsi-çiçeksi yorumu. Modern ve çok havalı bir niş ikon."),
            ("TIZIANA TERENZI KIRKE", "Unisex", "Çarkıfelek meyvesi, şeftali, ahududu ve sıcak kum. Egzotik bir meyve şöleni sunan güçlü bir tasarım."),
            ("LANCOME TRESOR", "Kadın", "Gül, şeftali ve kayısı çiçeğinin romantik harmonisi. Aşkın ve zarafetin pudralı, zamansız sembolü."),
            
            # 22-43
            ("VERSACE ABSOLU BRIGHT CRYSTAL", "Kadın", "Yuzu, nar ve ahududunun canlandırıcı etkisi. Daha yoğun, taze ve pırıl pırıl parlayan çiçeksi-meyvemsi bir rüya."),
            ("XERJOFF MORE THAN WORDS", "Unisex", "Oud, zengin meyveler ve gizemli oryantal notalar. Derin, sofistike ve son derece lüks bir kompozisyon."),
            ("YS BLACK OPIUM", "Kadın", "Siyah kahve, vanilya ve beyaz çiçeklerin adrenalin dolu buluşması. Enerji dolu, tatlı ve çekici."),
            ("CAROLINA HERRERA BAD BOY", "Erkek", "Beyaz karabiber, kakao ve tonka fasulyesi. Modern erkeğin asi, karanlık ve baharatlı tarafını yansıtan imza kokusu."),
            ("YS MON PARIS", "Kadın", "Çilek, ahududu ve datura çiçeği. Paris'in baş döndürücü aşk hikayelerinden ilham alan meyveli bir tutku."),
            ("BURBERRY BODY XX", "Unisex", "Şeftali, pelin otu, gül ve sandal ağacı. Tenle kusursuz bütünleşen, temiz, lüks ve pudralı bir dokunuş."),
            ("VIKTOR ROLF SPICEBOMB", "Unisex", "Pembe biber, tarçın, safran ve tütün. Sıcak, kışkırtıcı, patlayıcı ve son derece iddialı bir baharat bombası."),
            ("ARMANI MY WAY", "Kadın", "Tuberöz, portakal çiçeği ve Madagaskar vanilyası. Aydınlık, beyaz çiçeksi ve modern kadınların kokusu."),
            ("YST LIBRE INTENSE", "Kadın", "Fransız lavantası, Fas portakal çiçeği ve orkide akoru. Özgürlüğün daha yoğun, ateşli ve cesur dengesi."),
            ("TOM FORD TOBACCO VANILLE X", "Unisex", "Tütün yaprakları, vanilya, kakao ve baharatların zengin, gurmand ve lüks harmanı."),
            ("NASOMATTO BLACK AFGANO", "Erkek", "Esrar, kahve, tütün ve oud. Karanlık, hipnotize edici, dumansı ve oldukça sıra dışı bir tasarım."),
            ("KILIAN GOOD GIRL GONE BAD", "Kadın", "Osmanthus, yasemin ve mayıs gülü. Masum bir başlangıçtan baştan çıkarıcı bir çiçeğe dönüşen modern bir hikaye."),
            ("XERJOFF NAXOS 1861", "Unisex", "Limon, bal, tütün ve lavantanın İtalyan güneşi altındaki enfes uyumu. Zengin ve asil bir Akdeniz esintisi."),
            ("LACOSTE SPECIAL", "Erkek", "Ferah yeşil notalar ve sportif ahşap akorları ile hareketli, enerjik ve temiz bir gündüz kokusu."),
            ("GIVENCHY GENTLEMAN", "Erkek", "İris, karabiber ve siyah vanilyanın centilmen ve modern birleşimi. Karizmatik, pudralı ve zarif."),
            ("CREED AVENTUS", "Erkek", "Ananas, huş ağacı, meşe yosunu ve misk. Gücün, vizyonun ve başarının ikonik, dumansı-meyvemsi sembolü."),
            ("JEAN PAUL GAULTIER SCANDAL", "Kadın", "Bal, kan portakalı ve paçulinin lezzetli ve cesur birleşimi. Eğlenceli, tatlı ve kışkırtıcı."),
            ("KILLIAN ANGEL'S SHARE", "Unisex", "Konyak, meşe odunu, tarçın ve pralin. Sıcak, içki notalı, gurmand ve inanılmaz derecede lüks bir kış kokusu."),
            ("DIOR HYPNOTIC POISON", "Kadın", "Acı badem, vanilya ve Jacaranda ağacının hipnotik uyumu. Gizemli, yoğun ve çekici bir zehir."),
            ("AMOUGE REFLECTION MAN", "Erkek", "Beyaz çiçekler, biberiye ve sandal ağacının zarif, temiz ve maskülen yorumu. Kaliteli bir sabun hissiyatı."),
            ("GUCCI FLORA", "Kadın", "Şakayık, gül ve osmanthus çiçeklerinin neşeli, feminen ve taze bahar bahçesi yansıması."),
            ("BYREDO ROSE NOIR", "Kadın", "Geleneksel gül kokusunun karanlık, odunsu ve gizemli bir yorumu. Tutkulu ve sıra dışı bir şipre."),

            # 44-65
            ("FREDERIC MALLE PORTRAIT OF LADY", "Unisex", "Türk gülü, paçuli, sandal ağacı ve buhurun efsanevi ihtişamı. Sanat eseri niteliğinde, derin ve asil."),
            ("SOSPIRO ERBA PURA", "Unisex", "Sicilya narenciyeleri, tatlı meyveler ve misk. Mutluluk saçan, ferahlatıcı, kalıcı ve tatlı bir niş."),
            ("CHLOE NOMADE", "Kadın", "Mirabelle eriği, frezya ve meşe yosunu. Maceracı, özgür ruhlu ve modern bir şipre karakteri."),
            ("YSL Y", "Erkek", "Elma, zencefil, adaçayı ve vetiverin ferah ve aromatik birleşimi. Modern erkeğin taze ve şık imzası."),
            ("SOSPIRO ACCENTO", "Unisex", "Ananas, sümbül, pembe biber ve misk. Zarif, meyvemsi, çiçeksi ve oldukça iddialı bir aura."),
            ("GUCCI BLOOM", "Kadın", "Tuberöz, yasemin ve Rangoon sarmaşığı. Zengin ve pudralı beyaz çiçeklerin büyüleyici bir buketi."),
            ("CHLOE SIGNATURE", "Kadın", "Şakayık, litchi ve frezya. Klasikleşmiş, pudralı, sabunsu ve son derece zarif bir feminenlik."),
            ("HERMES CLASSIC", "Erkek", "Greyfurt, portakal, çakmaktaşı ve vetiverin topraksı ve narenciye ağırlıklı, benzersiz klasik dokunuşu."),
            ("LV NOMADE", "Erkek", "Deri, ahşap ve sıcak baharatların lüks seyahat hissini yaşatan, sofistike ve karakterli bir yorumu."),
            ("BURBERRY CLASSIC", "Erkek", "Elma, erik, sandal ağacı ve sedir. İkonik, sakin, sıcak ve zamansız bir İngiliz centilmeni kokusu."),
            ("ARMANI SI INTENSE", "Kadın", "Siyah frenk üzümü nektarı ve gülün yoğunlaştırılmış, cesur, tatlı ve tutku dolu versiyonu."),
            ("NARCISO RODRIGUEZ FOR HER SIYAH", "Kadın", "Misk, portakal çiçeği ve osmanthus. İpeksi, baştan çıkarıcı, temiz ve ikonik bir misk şöleni."),
            ("DELINA", "Kadın", "Türk gülü, litchi ve raventin tart, taze ve büyüleyici birleşimi. Prensesleri andıran lüks ve feminen bir niş."),
            ("GRAND SOIR", "Erkek", "Amber, vanilya ve tonka fasulyesinin Paris gecelerinden ilham alan sıcak, parıltılı ve büyüleyici harmanı."),
            ("VERY SEXY NIGHT", "Kadın", "Elma, siyah erik ve kadifemsi odunsu notaların karanlık, çekici ve modern gece kulübü aurası."),
            ("BOMBSHEL", "Kadın", "Çarkıfelek meyvesi, şakayık ve vanilya orkidesinin ferah, neşeli ve popüler meyvemsi-çiçeksi dansı."),
            ("CHANEL CHANCE", "Kadın", "Pembe biber, yasemin ve paçulinin şaşırtıcı, canlı, baharatlı ve çiçeksi şipre uyumu."),
            ("ARMANI CODE", "Erkek", "Zeytin çiçeği, tonka fasulyesi ve guayak ağacı. Derin, çekici, baharatlı ve maskülen bir klasik."),
            ("TOM FORD LOST CHERRY", "Unisex", "Siyah kiraz, acı badem ve likörün kışkırtıcı birleşimi. Gurmand, tatlı, yoğun ve eşsiz bir lezzet."),
            ("TOM FORD BLACK ORCHID", "Unisex", "Siyah orkide, çikolata, paçuli ve baharatlar. Karanlık, lüks, yoğun ve oldukça gotik bir başyapıt."),
            ("CREED AVENTUS FOR HER", "Kadın", "Yeşil elma, bergamot, gül ve paçuli. Güçlü, başarılı ve asil kadınlar için taze ve meyvemsi bir şipre."),
            ("LADY MILLION", "Kadın", "Ahududu, neroli, yasemin ve balın gösterişli ve tatlı buluşması. Zengin, iddialı ve altın değerinde bir koku."),

            # 66-87
            ("DIOR SAUVAGE ELIXIR", "Erkek", "Lavanta, baharatlar, sandal ağacı ve likör. Orijinalin çok daha karanlık, yoğun ve güçlü bir yorumu."),
            ("JPG LE MALE", "Erkek", "Nane, lavanta ve vanilyanın nostaljik ve efsanevi denizci kokusu. Ferah ama aynı zamanda sıcak bir çekicilik."),
            ("GUCCI GUILTY", "Erkek", "Limon, lavanta ve paçulinin kışkırtıcı ve modern uyumu. Kuralları yıkan, özgüvenli erkeklerin seçimi."),
            ("DIOR HOMME INTENSE", "Erkek", "İris, ambrette tohumu ve sedir ağacının pudralı, rujumsu, son derece lüks ve zarif bir harmanı."),
            ("LANCOME IDOL", "Kadın", "Isparta gülü, yasemin ve beyaz miskin aydınlık, tertemiz ve modern bir yansıması."),
            ("NARCISP RODRIGUES PURE HER BEYAZ", "Kadın", "Beyaz çiçekler, kaşmir ve imza niteliğindeki temiz misk. Saf, zarif, huzur verici ve tenle bütünleşen bir zarafet."),
            ("ONE MILLION ELIXIR", "Erkek", "Davana, Türk gülü ve tonka fasulyesinin zenginleştirilmiş, tatlı, yoğun ve baş döndürücü versiyonu."),
            ("PDM KALAN", "Erkek", "Kan portakalı, karabiber, meşe yosunu ve odunsu notalar. Ateşli, baharatlı, topraksı ve maskülen bir niş."),
            ("PDM LAYTON", "Erkek", "Elma, lavanta, vanilya ve biberin kusursuz dengesi. Hem taze hem sıcak, çekici ve son derece popüler bir imza."),
            ("DIOR JADORE", "Kadın", "Ylang-ylang, Şam gülü ve yaseminin altın sarısı, lüks, çiçeksi ve ışıltılı buketi."),
            ("ARMANI YOU INTELSY", "Erkek", "Pembe biber, vanilya ve konyak. Orijinalin daha sıcak, yoğun, likörlü ve kışlık, tatlı versiyonu."),
            ("BURBERRY GODDESS", "Kadın", "Üç farklı vanilya ekstraktı ve lavantanın sıcak, gurmand ve rahatlatıcı mükemmel birleşimi."),
            ("LV L'IMMENSITE", "Erkek", "Zencefil, greyfurt ve ambroksanın okyanus ferahlığı sunan, taze, keskin ve lüks bir yolculuğu."),
            ("ALTHAIR", "Unisex", "Bourbon vanilyası, tarçın ve pralin. Sıcak, gurmand, tatlı ve soğuk kış günlerinin vazgeçilmezi."),
            ("TORINO 21", "Unisex", "Nane, fesleğen, kekik ve limon. Tenis kortlarından ilham alan, son derece ferah, yeşil ve canlandırıcı bir yaz kokusu."),
            ("PARADISE GARDEN", "Erkek", "İncir yaprağı, yeşil notalar ve hindistan cevizi sütü. Tropikal, taze ve tatil hissiyatı veren egzotik bir rüya."),
            ("NISHANE ANI", "Unisex", "Zencefil, yeşil notalar, Türk gülü ve eşsiz bir vanilya. Dünya çapında övgü toplayan, baharatlı-gurmand bir şaheser."),
            ("NISHANE HACIVAT", "Erkek", "Ananas, greyfurt, bergamot ve meşe yosunu. Ferah, dumansı, meyvemsi ve performansı muazzam bir klasik."),
            ("NISHANE KARAGÖZ", "Erkek", "Siyah üzüm, ananas, oud ve vetiver. Hacivat'ın daha karanlık, tatlı ve oryantal çizgiye kayan oyuncu kardeşi."),
            ("GOD OF FIRE", "Erkek", "Mango, limon, zencefil ve odunsu notaların egzotik, tatlı, ferah ve mitolojik bir ateşi yansıtan dansı."),
            ("GUCCI GUILTY WOMEN", "Kadın", "Pembe biber, leylak ve paçuli. Cesur, kışkırtıcı, modern ve hafif pudralı bir feminenlik."),
            ("PRADA PARADOXE", "Kadın", "Neroli, amber ve beyaz misk. Hem taze çiçeksi hem de sıcak amberli, çok yönlü ve popüler bir modern tasarım."),

            # 88-109
            ("OUD MARICUJA", "Erkek", "Çarkıfelek meyvesi, deri, oud ve akigalawood. Meyvemsi açılışı odunsu bir karanlığa taşıyan iddialı bir parfüm."),
            ("DONNA", "Kadın", "Gül, iris, vanilya ve derinin pudralı, romantik ve zarif İtalyan zarafeti."),
            ("AFRICAN LEATHER", "Unisex", "Kakule, safran, deri ve vetiver. Afrika savanlarının sıcaklığını ve vahşiliğini şişeleyen baharatlı bir deri kokusu."),
            ("BURBERRY HERO", "Erkek", "Bergamot, çam ağacı ve ardıç. Ormanların taze, yeşil, maskülen ve odunsu enerjisi."),
            ("GANYMEDE", "Unisex", "Mandalina, deri, safran ve mineralli notalar. Uzay ferahlığı veren, modern, soğuk ve metalik bir başyapıt."),
            ("LE MALE ELIXIR", "Erkek", "Tonka fasulyesi, lavanta ve tütün. Efsanevi kokunun çok daha sıcak, balzamik, tatlı ve çekici hali."),
            ("KENZO HOMME MARINE", "Erkek", "Deniz notaları, ylang-ylang ve sandal ağacı. Güneşli bir yaz gününün ferah ve okyanus esintili yansıması."),
            ("TRIUMPH OF BACCHUS", "Unisex", "Rom, beyaz şeftali, yeşil elma ve tütün. Kutlamaların ve tanrıların içkisini andıran, gurmand, tatlı ve sarhoş edici."),
            ("TIZIANA TERENZI TYRENUM", "Unisex", "Güney İtalya denizlerinin esintisi, bergamot, ardıç ve deniz tuzunun birleştiği lüks bir sucul niş."),
            ("ORTO PARISI RISVELLIUM", "Unisex", "Hayvansal, yoğun ahşaplar ve misk. Derin, kışkırtıcı, karanlık ve doğanın gizli sırlarını barındıran bir tasarım."),
            ("MARC ANTOINE BARROIS TILIQ", "Unisex", "Zarif çiçekler, yeşil notalar ve odunsu akorların birleştiği yenilikçi, modern ve temiz bir kompozisyon."),
            ("AMOUGE GUIDANCE", "Kadın", "Armut, fındık, osmanthus, gül ve sandal ağacı. Tatlı, kremsi, çok güçlü ve son yılların en dikkat çekici parfümü."),
            ("KAYALI MARSHMALLOW", "Kadın", "Hatmi çiçeği, vanilya, portakal çiçeği. Tatlı, şekerli, pamuk gibi yumuşak ve gurmand bir koku."),
            ("KILIAN BLUE MOON GINGER DASH", "Unisex", "Zencefil, limon, konyak ve ferah akorlar. Yaz geceleri için tasarlanmış, buzlu bir kokteyl hissiyatı."),
            ("LOUIS VUITTON AFTERNOON SWIM", "Unisex", "Mandalina, bergamot ve portakal. Yazın coşkusunu, enerjisini ve narenciye ferahlığını yansıtan lüks bir serinlik."),
            ("ARABIAN TONKA", "Unisex", "Safran, gül, tonka fasulyesi ve oud. Orta Doğu'nun gizemini Paris şıklığıyla birleştiren tatlı ve baharatlı niş."),
            ("TOM FORD FUCKING FABULOUS", "Unisex", "Acı badem, deri, lavanta ve tonka fasulyesi. İsmi gibi iddialı, kışkırtıcı, pudralı ve aromatik bir deri."),
            ("TIZIANA TERENZI GUMIN", "Unisex", "Ananas, mandalina, portakal ve amber. Ferah, tatlı, meyveli ve performansı muazzam bir İtalyan yaz klasiği."),
            ("PROFUMUM ROMA - ACQUA DI SALE", "Unisex", "Tuz, mersin otu, deniz yosunu ve sedir. İtalyan kıyılarının taze, doğal ve tuzlu deniz havasını doğrudan hissettiren bir eser."),
            ("LOUIS VUITTON IMAGINATION", "Erkek", "Siyah çay, Çin bergamotu ve ambroksan. Sabunsu, taze, temiz, zarif ve inanılmaz derecede kalıcı bir ferahlık."),
            ("XERJOFF ALEXANDRIA 2", "Unisex", "Elma, tarçın, gül, lavanta ve Laos oudu. Krallara layık, asil, pudralı, odunsu ve zengin bir şaheser."),
            ("CREED AVENTUS ABSOLU", "Erkek", "Orijinal DNA'ya eklenen greyfurt, tarçın ve vetiver dokunuşlarıyla daha yoğun, kışlık ve baharatlı bir Aventus yorumu."),

            # 110-131
            ("GIVENCHY L'INTERDIT ROUGE", "Kadın", "Kan portakalı, zencefil, tuberöz ve paçuli. Baharatlı, sıcak, şehvetli ve kırmızının ateşini yansıtan bir gece kokusu."),
            ("DOLCE GABBANA DEVOTION", "Kadın", "Şekerlenmiş limon, portakal çiçeği ve Madagaskar vanilyası. Fırından yeni çıkmış limonlu bir keki andıran lezzetli gurmand."),
            ("SOSPIRO VIBRATO", "Erkek", "Bergamot, greyfurt, zencefil ve pudralı notalar. Tygar DNA'sını andıran, çok kalıcı, ferah ve lüks bir narenciye-çiçek harmanı."),
            ("KAYALI 28", "Unisex", "Esmer şeker, tonka fasulyesi, amber ve vanilya. Tatlı, kremsi, lezzetli ve tam bir vanilya severlerin rüyası."),
            ("BURBERRY HER", "Kadın", "Çilek, ahududu, vişne, böğürtlen ve meşe yosunu. Baccarat Rouge'u anımsatan, şekerli, meyveli ve enerjik bir tasarım."),
            ("BOIS IMPERIAL EXTRAIT", "Unisex", "Akigalawood, vetiver, fesleğen ve karabiber. Modern, odunsu, baharatlı, metalik ve performansı ile öne çıkan efsane."),
            ("PACO RABANNE VICTORY ELIXIR", "Erkek", "Vanilya, amber ve tütsünün sıcak, balzamik ve tatlı buluşması. Güçlü, kalıcı ve gece için ideal bir kış parfümü."),
            ("MATIERE PREMIERE VANILLIA POWDER", "Unisex", "Madagaskar vanilyası, Hindistan cevizi, palo santo. Doğal, pudralı, odunsu ve boğmayan, çok kaliteli bir vanilya yorumu."),
            ("LE MALE LE PARFUME - EXTRAIT DE PARFUME", "Erkek", "Kakule, iris, lavanta ve vanilya. Le Male serisinin en zarif, pudralı, sofistike ve geceye yakışan baharatlı versiyonu."),
            ("OUD FOR GREATNES", "Erkek", "Safran, muskat, lavanta ve oud. Gizemli, görkemli, sıcak baharatlı ve kesinlikle dikkat çekici, asil bir duruş."),
            ("BDK - GRIS CHARNEL EXTRAIT", "Unisex", "İncir, siyah çay, kakule ve sandal ağacı. Orijinalin daha derin, odunsu, sıcak baharatlı ve kalıcı hale getirilmiş, yağmurlu günlere yakışan hali."),
            ("AMOUAGE - BEACH HUT", "Unisex", "Nane, galbanum, vetiver ve sarmaşık. Plaj kulübelerinden ilham alan, yemyeşil, aromatik, çok farklı ve ferah bir erkek parfümü."),
            ("MEMO - MARFA", "Unisex", "Tuberöz, portakal çiçeği ve agav. Teksas çöllerinden ilham alan, sıcak, kremsi, beyaz çiçeksi ve tatlı bir yaz rüyası."),
            ("KILLIAN - BLACK PHANTOM", "Unisex", "Korsan gemilerinden ilham alan rom, kahve, çikolata ve karamel. Gurmand, karanlık, tatlı ve tehlikeli bir cazibe."),
            ("CHANEL - BLUE DE CHANEL", "Unisex", "Greyfurt, zencefil, tütsü ve sedir ağacı. Mavi parfümlerin atası; taze, duş ferahlığında, şık, ofis dostu ve son derece maskülen."),
            ("TOM FORD - NOIR EXTREM", "Unisex", "Kakule, kulfi tatlısı, vanilya ve amber. Gecenin karanlığında parlayan, tatlı, kremsi, baharatlı ve seksi bir imza kokusu."),
            ("EX NIHILO - BLUE TALISMAN", "Unisex", "Armut, bergamot, misk ve ambroksan. Mavi, ferah, hafif meyveli, modern, lüks ve enerjiyi yükselten bir tılsım."),
            ("TOM FORD - OMBRE LEATHER", "Unisex", "Kakule, deri ve yasemin. Vahşi Batı'nın geniş çöllerini anımsatan, gerçekçi, pürüzsüz, çiçeksi ve çok kaliteli bir deri parfümü."),
            ("HUGO BOSS - BOTTLED ABSOLU", "Unisex", "Kavrulmuş elma, tarçın, mür ve odunsu akorlar. Klasik Boss DNA'sının en sıcak, yoğun, tatlı ve kışlık extrait yorumu."),
            ("PACO RABANNE - ONE MILLION LUCKY", "Unisex", "Fındık, bal, erik ve odunsu notalar. Klasik One Million'dan çok farklı, tatlı, gurmand, meyveli ve çok eğlenceli bir koku."),
            ("BALMAIN - CARBONE", "Unisex", "İncir, karabiber, tütsü ve vetiver. Karanlık, odunsu, biberli ve takım elbiseye çok yakışan, ciddi, sofistike bir tasarım."),
            ("NISHANE- FAVONIUS", "Unisex", "Gül, tütsü, oud ve paçuli. Antik Roma mitolojisinden esinlenen, odunsu-çiçeksi, asil ve mistik bir Türk niş parfümü."),

            # 132-153
            ("INITIO - SIDE EFFECT", "Unisex", "Rom, vanilya, tütün ve tarçın. Tatlı, içki notalı, gurmand, kışkırtıcı ve ismi gibi yan etkisi yüksek bir başyapıt."),
            ("KAYALI - EDEN SPARKLING", "Unisex", "Liçi, siyah frenk üzümü, pembe elma. Şampanya ferahlığında, meyveli, neşeli, tatlı ve pırıl pırıl parlayan bir tasarım."),
            ("KAYALI - EDEN JUIC APPLE 01", "Unisex", "Kırmızı elma, orman meyveleri, yasemin. Sulu, ısırılmış taze bir elmayı anımsatan, iştah açıcı, tatlı ve enerjik."),
            ("KAYALI - YUM PISTACHIO GELATO", "Unisex", "Antep fıstığı, dondurma, pamuk şeker, marshmallow. Lezzetli bir İtalyan fıstıklı dondurması gibi, gurmand, kremsi ve çok tatlı."),
            ("ARMANI - YOU AMBER", "Unisex", "Amber, vanilya ve baharatların sıcak dokunuşu. Stronger With You serisinin Orta Doğu esintili, lüks ve reçineli versiyonu."),
            ("ARMANI - YOU SANDALWOOD", "Unisex", "Sandal ağacı, baharatlar ve odunsu notalar. Serinin pürüzsüz, kremsi, odunsu ve sofistike tarafı."),
            ("MFK - OUD SATIN MOOD", "Unisex", "Bulgar gülü, Türk gülü, Laos oudu, vanilya ve menekşe. İpek bir kumaş gibi tene dokunan, pudralı, tatlı ve muazzam lüks bir oud-gül kombosu."),
            ("CREED - SILVER MOUNTAIN WATER", "Unisex", "Yeşil çay, bergamot, frenk üzümü, misk. Alpler'in eriyen buzullarından ilham alan, soğuk, temiz, metalik ve çay ferahlığında bir efsane."),
            ("SERGE LUTENS - CHERGUI", "Unisex", "Tütün, bal, saman, buhur. Fas çöllerinde esen kuru ve sıcak rüzgarları şişeleyen, tatlı, oryantal, baharatlı ve kült bir niş."),
            ("CLIVE CHRISTIAN BLONDE AMBER", "Erkek", "Sarı amber, rom, kuru meyveler, tütün. Dünyanın en pahalı parfümlerinden biri; zengin, gurmand, tatlı, dumansı ve ihtişamlı."),
            ("ROJA ISOLA BLUE", "Erkek", "Limon, bergamot, elma, yeşil çimen. Akdeniz kıyılarının lüks yat tatillerini anımsatan, narenciye ağırlıklı, taze, şık ve sofistike bir yazlık."),
            ("SLUMBERHOUSE KISTE", "Unisex", "Şeftali, bal, tütün, burbon. Kavurucu güneşte kalmış olgun meyveler ve yoğun, yapışkan, tatlı, çok farklı ve deneysel bir gurmand."),
            ("SOSPIRO IL PADRINO", "Unisex", "Oud, gül, baharatlar ve deri. İtalyan şıklığını Orta Doğu lüksüyle harmanlayan, güçlü, karakterli ve iddialı bir tasarım."),
            ("TOM FORD BLAC LACQUER", "Erkek", "Abanoz ağacı, makassar, şakayık, siyah rum. Yeni, karanlık, lüks, odunsu ve pürüzsüz siyah lake cilayı andıran özel seri parfüm."),
            ("VICTORIA SECRET TEASE CREME CLOUD", "Kadın", "Vanilya merengi, sandal ağacı çiçeği, şeffaf misk. Yumuşak, kremsi, havadar, tatlı ve adeta bir bulutun üzerinde yatıyormuş hissi veren hafif bir koku."),
            ("XERJOFF TONY IOMMI DEIFIED", "Erkek", "Deri, safran, elma, rom. Black Sabbath'ın efsanevi gitaristinden ilham alan, rock'n roll ruhlu, tatlı, meyveli ve karanlık bir şaheser."),
            ("INITIO NARCOTIC DELIGHT", "Unisex", "Vişne, konyak, vanilya, tütün. Baş döndürücü, tatlı, içki notalı, gurmand ve kışkırtıcı bir meyve şöleni."),
            ("LOUIS VUITTON METEORE", "Erkek", "Mandalina, Sicilya portakalı, karabiber, vetiver. Sabunsu temizliği ferah baharatlarla harmanlayan, taze, şık ve enerjik bir lüks."),
            ("MAISON CRIVELLI HIBISCUS MAHAJAD", "Unisex", "Hibiskus çiçeği, gül, nane, vanilya. Çiçeksi, tatlı, ferahlatıcı çay hissi veren ve performansı inanılmaz boyutlarda olan bir niş."),
            ("MAISIN CRIVELLI SAFRAN SECRET", "Unisex", "Safran, deri, baharatlar. Soğuk, gizemli, baharatlı ve modern deri parfümü sevenler için şık ve pürüzsüz bir kompozisyon."),
            ("MEMO OCEAN LEATHER", "Erkek", "Mandalina, deri, vetiver, fesleğen. Okyanus ferahlığını yumuşak deri notalarıyla birleştiren, taze, aromatik ve sıra dışı bir marin deri."),
            ("MONTALE HONEY AOUD", "Unisex", "Bal, oud, tarçın, vanilya. Tatlı balın ve odunsu oudun sıcak, baharatlı, kışlık ve çok güçlü bir performansa sahip birleşimi."),

            # 154-175
            ("NASOMATTO BARAONDA", "Unisex", "Viski, gül, ambrette, odunsu notalar. Boş bir viski fıçısını kokluyormuş hissi veren, içkili, tatlı, odunsu ve çok gerçekçi bir şaheser."),
            ("NISHANE FAN YOUR FLAMES", "Unisex", "Hindistan cevizi, rom, tütün, sedir. Nargile dumanı, tropikal tatlılık ve odunsu sertliğin birleştiği benzersiz bir koku."),
            ("PENHALIGON'S BLAZING MISTER SAM", "Unisex", "Kakule, tarçın, karabiber, sedir. Sıcak, baharatlı, odunsu, hafif tatlı ve tam bir İngiliz centilmenine yakışan, karakterli bir Portre serisi üyesi."),
            ("AMOUAGE INTERLUDE 53", "Erkek", "Kekik, buhur, oud, deri. Mavi canavarın %53 ekstrakt konsantrasyonlu, çok daha yoğun, pürüzsüz, dumansı ve efsanevi hali."),
            ("KILIAN OLD FASHIONED", "Erkek", "Buğday absolüsü, sedir, tolu balsamı. Eski usul malt viski yıllandırma fıçılarından esinlenen, lüks, odunsu ve olgun bir imza."),
            ("BYREDO TOBACCO MANDARIN", "Erkek", "Mandalina, kişniş, tütün, oud. Narenciyenin parlaklığının karanlık tütün ve oud ile buluştuğu, zıtlıkların uyumu."),
            ("CLIVE CHRISTIAN HEDONISTIC", "Erkek", "Vişne, tütün, vanilya, amber. Sınırları zorlayan lüks, meyvemsi, dumansı, tatlı ve baştan çıkarıcı, muazzam zengin bir koku."),
            ("DOLCE GABBANA LIGHT BLUE POUR HOMME ITALIAN LOVE", "Erkek", "Greyfurt, bergamot, ozonik notalar, vetiver. Orijinalin çok daha narenciyeli, gerçekçi greyfurt kabuğu kokan ve odunsu yazlık versiyonu."),
            ("GIARDINI DI TOSCANA BIANCO LATE", "Unisex", "Karamel, bal, vanilya, beyaz misk. Sütlü bir tatlı gibi, çok kremsi, gurmand, inanılmaz popüler ve bağımlılık yaratan bir lezzet."),
            ("EMPORIO ARMANI STRONGER WITH YOU TOBACCO", "Erkek", "Tütün, vanilya, kestane. Klasik DNA'ya eklenen yoğun, tatlı ve karanlık tütün yapraklarıyla kışlık, çok güçlü bir flanker."),
            ("GUCCI THE VOICE OF THE SNAKE", "Erkek", "Oud, paçuli, safran. Yılanın gizemini ve karanlığını yansıtan, topraksı, derin, odunsu ve lüks Alchemist's Garden serisi harikası."),
            ("SCANDAL POUR HOMME", "Erkek", "Karamel, tonka fasulyesi, adaçayı, vetiver. Kralın dönüşü; çok tatlı, dikkat çekici, gece kulüplerinin vazgeçilmezi modern bir erkek parfümü."),
            ("INITIO ABSOLUTE APHRODISIAC", "Unisex", "Vanilya, kunduz yağı (castoreum), amber. Hayvansal notaların tatlı vanilyayla harmanlandığı, vahşi, sıcak ve adı gibi mutlak bir afrodizyak."),
            ("OUD FOR GREATNESS", "Erkek", "Safran, muskat, lavanta, oud. Lüks, ihtişamlı, tatlımsı-baharatlı, takım elbiseye çok yakışan, saygı uyandıran bir güç simgesi."),
            ("PDM LAYTON EXCLUSIF", "Erkek", "Badem, elma, vanilya, oud, kahve. Layton'un tatlılığının karanlık odunlar ve kahveyle harmanlanmış, daha derin, kışlık ve maskülen hali."),
            ("GUERLAIN AMBRE SAMAR", "Unisex", "Acı badem, vanilya, baharatlar. Guerlain'in klasikleşmiş amber ve gurmand uzmanlığının nadide, sıcak ve büyüleyici bir örneği."),
            ("BOSS THE SCENT ELIXIR", "Erkek", "Kırmızı biber, lavanta, sandal ağacı. Serinin en yoğun, ateşli, baharatlı, tatlı ve deri hissiyatlı gece parfümü."),
            ("BOSS THE SCENT ELIXIR FOR HER", "Kadın", "Pembe biber, atropa belladonna, amber. Kışkırtıcı, tatlı, gizemli, yoğun ve çekici bir feminen gece iksiri."),
            ("LV ORAGE", "Unisex", "Paçuli, bergamot, iris. Fırtına öncesi sessizliği anımsatan, topraksı, taze, temiz ve son derece şık bir odunsu niş."),
            ("YSL SUPREME BOUQUET", "Unisex", "Tuberöz, ylang-ylang, amber. Oryantal ve zengin beyaz çiçeklerin sıcak amberle buluştuğu lüks, kremsi ve tatlı bir buket."),
            ("V&R FLOWERBOMB", "Kadın", "Çay, orkide, yasemin, gül, paçuli. Çiçeklerin patlaması; tatlı, pudralı, çok ünlü ve son derece çekici bir modern klasik."),
            ("TOM FORD TUSCAN LEATHER", "Erkek", "Deri, ahududu, safran, kekik. Lüks bir İtalyan deri ceketinin içine ezilmiş ahududuların kokusu, sert, meyveli ve kusursuz bir deri başyapıtı."),

            # 176-197
            ("INITIO REHAB", "Unisex", "Lavanta, tütün, sedir, vanilya. Spicebomb'un daha kremsi, pürüzsüz, kaliteli, yatıştırıcı ve lüks niş versiyonu gibi hissettiren taze baharatlı koku."),
            ("LV SYMPHONY", "Unisex", "Greyfurt, bergamot, zencefil. Louis Vuitton'un narenciye şöleni; yaz için son derece ferah, doğal, tazeleyici ve lüks bir senfoni."),
            ("DOLCE GABBANA K EDP", "Erkek", "Kan portakalı, ardıç, pimento, incir sütü. Kralların kokusu; baharatlı, meyveli, aromatik, tatlı ve odunsu maskülen tasarım."),
            ("NASOMATTO SADONASO", "Unisex", "Kahve, misk, tütün, hayvansal notalar. Gizli arzuları yansıtan, pudralı, terli, tatlı, çok kışkırtıcı ve sınırları zorlayan sıra dışı bir deneyim."),
            ("JO MALONE MYRRH&TONKA", "Unisex", "Mür reçinesi, tonka fasulyesi, lavanta. Soğuk havalara yakışan, sıcak, tatlı, bademsi, reçineli, çok zarif ve rahatlatıcı bir imza."),
            ("YSL TUXEDO", "Unisex", "Paçuli, amber, menekşe yaprağı, karabiber. Smokin şıklığını şişeleyen; baharatlı, yeşil, hafif tatlı, çok klas, zarif ve lüks bir gece kokusu."),
            ("ORTO PARISI BOCCANERA", "Unisex", "Bitter çikolata, zencefil, karabiber, biberiye. Black Afgano'nun daha çikolatalı, baharatlı, gurmand, sıcak ve acımsı-tatlı yoğun kardeşi."),
            ("NICOLAI PATCHOULI INTENSE", "Unisex", "Paçuli, sardunya, lavanta, portakal. Geleneksel toprak kokan paçulilerden farklı; sabunsu, yeşil, ferah, aromatik ve şipre karakterli bir efsane."),
            ("MAB ENCELADE", "Unisex", "Ravent, vetiver, deri, sandal ağacı. Ormanın derinliklerinde volkanik bir patlama gibi; yeşil, dumansı, odunsu, inanılmaz farklı ve kalıcı."),
            ("ARMANI MY WAY YLANG", "Kadın", "Ylang-ylang, tuberöz, portakal çiçeği, vanilya. Tropikal tatil esintisi sunan; kremsi, beyaz ve sarı çiçekli, tatlı, güneşli bir versiyon."),
            ("HERMES H24", "Erkek", "Adaçayı, nergis, sclarene. Geleneksel maskülenliğin dışına çıkan; sıcak buharlı ütü hissi veren, botanik, metalik, yeşil ve çok modern bir ofis kokusu."),
            ("MONTALE INFINITY", "Unisex", "Siyah kiraz, erik, oud, vanilya, deri. Tatlı meyvelerin oud ve deriyle karanlık, sıcak, baharatlı, sonsuz kalıcılığa sahip birleşimi."),
            ("GUERLAIN SANTAL ROYAL", "Unisex", "Sandal ağacı, gül, oud, deri, şeftali. Orta Doğu'nun gizemiyle Fransız zarafetinin buluştuğu; tatlımsı, karanlık, odunsu, asil ve lüks bir tasarım."),
            ("AZZARO THE MOST WANTED PARFUM", "Erkek", "Kırmızı zencefil, odunsu notalar, vanilya. Son derece tatlı, sıcak, baharatlı, karamelize hissiyatlı, iddialı ve gece kullanımına uygun bir iltifat makinesi."),
            ("PDM PEGASUS EXCLUSIF", "Erkek", "Acı badem, vanilya, oud, kakule. Orijinal Pegasus'un metalik badem yapısının karanlık oud ve baharatlarla daha yoğun, derin, kışlık ve asil hale getirilmiş şekli."),
            ("GENYUM PAINTER", "Unisex", "Siyah biber, deniz yosunu, ardıç. Bir ressamın atölyesindeki boya ve keten tuval kokularını anımsatan; aromatik, baharatlı, ferah ve sanatsal bir niş."),
            ("ARMANI YOU ABSOLUTELY", "Unisex", "Rom, vanilya, kestane, lavanta. İçki notalarıyla zenginleştirilmiş; sıcak, tatlı, yoğun, kış aylarında iç ısıtan efsanevi bir gurmand."),
            ("KIRKE OVERDOSE", "Unisex", "Meyveler, tutku meyvesi, misk. Zaten güçlü olan Kirke'nin çok daha yoğun, meyve şöleni sunan, tatlı ve performans canavarı hali."),
            ("OUD ZARIAN", "Unisex", "Oud, gül, safran, baharatlar. Zengin, oryantal, sıcak, gösterişli ve kraliyet ailesi lüksünü teninize taşıyan geleneksel bir niş parfüm."),
            ("EROS NAJIM", "Unisex", "Yeşil elma, nane, vanilya, odunsu notalar. Klasik Eros DNA'sının Orta Doğu tarzı yoğun baharat ve reçinelerle harmanlandığı özel ve kışkırtıcı bir versiyon."),
            ("ROJA ELSIUM", "Unisex", "Greyfurt, limon, vetiver, ambergris. Bir yaz bahçesindeki taze narenciyelerin ve lüksün kokusu; şık, ferah, kaliteli, pürüzsüz ve zamansız."),
            ("DONNA BORN IN ROMA INTENSE", "Unisex", "Bourbon vanilya, yasemin, benzoin. Roma gecelerinin romantizmini yansıtan; tatlı, çiçeksi, kremsi, yoğun, baştan çıkarıcı ve modern bir tasarım."),

            # 198-219
            ("AVENTUS DUMANSI", "Erkek", "Ananas, huş ağacı, meşe yosunu, misk. Efsanevi Aventus'un daha ilk yıllarındaki o meşhur isli, odunsu, karanlık ve daha maskülen dumansı batch karakteri."),
            ("PASIFIC CHILL", "Unisex", "Nane, fesleğen, kişniş, limon, kayısı. Kaliforniya kıyılarının detoks içeceklerinden ilham alan; ferah, bitkisel, meyveli, çok taze ve huzur verici."),
            ("ORTA PARISI BERGAMASK", "Unisex", "Bergamot, misk, lavanta. Ferah narenciye açılışının altından Orto Parisi'nin imzası o hayvansal, terli, yoğun ve kirli misk karakterinin çıktığı zıtlıklar eseri."),
            ("ORTA PARISI COUIUM", "Unisex", "Deri, paçuli, tütün, menekşe. Giyilmiş eski bir deri ceket, is ve toprağın vahşi, karanlık, dumansı, çok güçlü ve son derece iddialı buluşması."),
            ("HUGO BOSS BOTTLE PASIFIC", "Unisex", "Hindistan cevizi, limon, tuz, selvi. Boss Bottled DNA'sının plaj hissiyatı veren; tropikal, tatlımsı, tuzlu ve tatil ruhunu yansıtan yazlık versiyonu."),
            ("REBUL ISTANBUL", "Unisex", "Tarçın, karanfil, safran, vanilya, odunsu notalar. Mısır Çarşısı'nın baharatlı, sıcak, gizemli ve nostaljik atmosferini yansıtan imza bir koku."),
            ("MYSELF LE PARFÜM", "Unisex", "Portakal çiçeği, paçuli, odunsu notalar, karabiber. Modern maskülenliğin çiçeksi ve sabunsu temizliğini karanlık odunlarla harmanlayan, şık ve yoğun tasarım."),
            ("ARMANI YOU OUD", "Unisex", "Oud, lavanta, vanilya. Stronger With You tatlılığının güçlü ve karanlık oud notasıyla birleştiği; lüks, oryantal, sıcak ve reçineli kışlık parfüm."),
            ("MUSK RAVAGEUR", "Unisex", "Lavanta, karanfil, tarçın, vanilya, misk. İsmi gibi 'Yıkıcı Misk'; baharatlı, hayvansal, tatlı, son derece baştan çıkarıcı, kirli ama çok seksi bir başyapıt."),
            ("TUBEREUSE ASTRALE", "Unisex", "Tuberöz, tarçın, osmanthus, deri. Sümbülteber çiçeğinin yıldızlara uzanan, kremsi, baharatlı, meyvemsi ve uzaysal bir derinlik barındıran büyüleyici yorumu."),
            ("AMOUAGE OUTLANDS", "Unisex", "Buhur, elemi, paçuli, oud, baharatlar. Amouage'ın çöl manzaralarını anımsatan; reçineli, dumanlı, zengin, oryantal, lüks ve çok katmanlı niş sanatı."),
            ("ARMANI ACQUA GIO PROFUMO", "Erkek", "Deniz notaları, bergamot, tütsü, paçuli. Okyanus dalgalarının siyah kayalara çarpması gibi; ferah, dumansı, olgun, karanlık, şık ve efsanevi bir başyapıt."),
            ("BVLGARI MAN IN BLACK", "Erkek", "Baharatlar, rom, tütün, deri, tonka fasulyesi. Spicebomb'un daha olgun, lüks, takım elbiseye yakışan; sıcak, içki notalı, karizmatik ve baharatlı abisi."),
            ("JPG ULTRA MALE", "Erkek", "Armut, vanilya, tarçın, nane, lavanta. Le Male'in parti canavarı kardeşi; çok tatlı, sakızımsı meyveli, yüksek sesli, dikkat çekici ve iltifat toplayan gece kokusu."),
            ("ROSENDO MATEU NO 5", "Unisex", "Karanfil, baharatlar, amber, vanilya, misk. Buram buram lüks kokan; sıcak, çiçeksi, hafif kauçuksu, gurmand, çok güçlü ve son yılların en popüler nişlerinden."),
            ("ANGEL SHARE ON THE ROCKS", "Unisex", "Konyak, tarçın, pralin, odunsu notalar. Meşe fıçılarda yıllanmış pahalı bir içkinin, buzla servis edilmiş hissi veren; tatlı, gurmand, lüks ve kışkırtıcı yorumu."),
            ("212 VIP", "Erkek", "Çarkıfelek meyvesi, votka, cin, nane, deri. Özel partilerin aranan ismi; içki notalı, meyveli, eğlenceli, enerjik, tatlı ve modern gece kulübü parfümü."),
            ("OUD MALAKI", "Unisex", "Tütün, oud, baharatlar, greyfurt, deri. Chopard'ın altın değerindeki lüks tasarımı; sıcak, maskülen, baharatlı, zengin ve gerçek bir beyefendi kokusu."),
            ("GISADA AMBASSADOR", "Erkek", "Elma, mango, karabiber, vanilya, vetiver. Sauvage ferahlığının tropikal meyvelerle tatlandırılmış hali; çok popüler, enerjik, çok yönlü ve iltifat canavarı."),
            ("DIESEL ONLY THE BRAVE", "Erkek", "Limon, deri, amber, menekşe, kişniş. Yumruk şeklindeki ikonik şişesiyle özdeşleşen; taze, pudralı, deri ağırlıklı, dinamik, genç ve cesur bir klasik."),
            ("GUERLAIN L'HOMME IDEAL", "Erkek", "Acı badem, deri, vanilya, tonka fasulyesi, kiraz. Mükemmel erkeğin kokusu; amaretto likörü hissiyatlı, tatlı, pudralı, çok zarif, şık ve çekici."),
            ("BYREDO BAL D'AFRIQUE", "Unisex", "Kadife çiçeği, limon, vetiver, siyah frenk üzümü. Afrika'nın sıcak güneşini ve Paris'in romantizmini birleştiren; sabunsu, temiz, meyvemsi-odunsu, eşsiz ve zarif.")
        ]

        eklenen_sayi = 0

        for name, category_name, description in perfume_data:
            # 1. Kategoriyi bul veya yoksa oluştur
            category, _ = Category.objects.get_or_create(name=category_name)

            # 2. Parfümü bul veya yoksa oluştur
            perfume, created = Perfume.objects.get_or_create(
                name=name,
                defaults={
                    'category': category,
                    'description': description,
                    'price': 1000.00,  # Fiyatları admin panelinden toplu güncelleyebilirsin
                    'image': ''
                }
            )
            
            if created:
                eklenen_sayi += 1

        self.stdout.write(self.style.SUCCESS(f'İşlem başarıyla tamamlandı! {eklenen_sayi} adet parfüm, özel SEO açıklamalarıyla veritabanına eklendi.'))